language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install pylint -r requirements.txt --use-mirrors --allow-external argparse --allow-unverified argparse
script:
  - pylint --errors-only --additional-builtins=raw_input smugline.py
